name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  format:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: 'node_modules'
          path: 'node_modules'
          compression-level: 9

      - name: Check formatting
        run: pnpm prettier . --check

  lint:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: 'node_modules'
          path: 'node_modules'
          compression-level: 9

      - name: Lint
        run: pnpm lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: 'node_modules'
          path: 'node_modules'
          compression-level: 9

      - name: Run tests
        run: pnpm test 