name: Setup Node.js Environment

on:
  workflow_call:
    outputs:
      node_modules:
        description: "Path to node_modules artifact"
        value: 'node_modules'

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: '~/.local/share/pnpm/store'
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: 'node_modules'
          path: 'node_modules'
          retention-days: 1
          compression-level: 9 